name: 'Setup Vulkan SDK multiplatform'
description: 'Setup Vulkan SDK using GitHub Actions'
inputs:
  version:
    description: 'Vulkan SDK version to install'
    default: '1.3.296.0'
    required: true
  components:
    description: 'List of Vulkan SDK components to install (e.g., Vulkan-Headers, Vulkan-Loader, Glslang)'
    default: 'Vulkan-Headers,Vulkan-Loader'
    required: true
  cache:
    description: 'Enable caching for Vulkan SDK'
    default: 'false'
    required: false
runs:
  using: "composite"
  steps:
    # check version
    - name: Version setup
      shell: bash
      run: |
          if [[ "${{ inputs.version }}" == "latest" ]]; then
            page=$(curl -s https://sdk.lunarg.com/sdk/home)
            VERSION_VULKAN_TO_DOWNLOAD=$(echo "$page" | sed -n 's/.*vulkansdk-macos-\([0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+\)\.zip.*/\1/p' | head -n1)
          else
            VERSION_VULKAN_TO_DOWNLOAD="${{ inputs.version }}"
          fi
          echo "VERSION_VULKAN_TO_DOWNLOAD=$VERSION_VULKAN_TO_DOWNLOAD" >> $GITHUB_ENV

    # windows
    - name: Download Vulkan SDK (Windows)
      if: runner.os == 'Windows'
      shell: bash
      run: |
        newer=$(printf "%s\n%s\n" "${{ inputs.version }}" "1.4.309.0" | sort -V | tail -n1)
        if [[ "$newer" == "$VERSION_VULKAN_TO_DOWNLOAD" ]]; then
          curl -LO "https://sdk.lunarg.com/sdk/download/$VERSION_VULKAN_TO_DOWNLOAD/windows/VulkanSDK-X64-$VERSION_VULKAN_TO_DOWNLOAD-Installer.exe"
        else
          curl -LO "https://sdk.lunarg.com/sdk/download/$VERSION_VULKAN_TO_DOWNLOAD/windows/VulkanSDK-$VERSION_VULKAN_TO_DOWNLOAD-Installer.exe"
        fi
        start VulkanSDK-$VERSION_VULKAN_TO_DOWNLOAD-Installer.exe /S /COMPONENTS="${{ inputs.components }}"
        echo "VULKAN_SDK=C:\\VulkanSDK\\$VERSION_VULKAN_TO_DOWNLOAD" >> $GITHUB_ENV
        echo "Path=$VULKAN_SDK\\Bin;$Path" >> $GITHUB_ENV

    # linux
    - name: Install Vulkan SDK (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        curl -LO https://sdk.lunarg.com/sdk/download/$VERSION_VULKAN_TO_DOWNLOAD/linux/vulkansdk-linux-x86_64-$VERSION_VULKAN_TO_DOWNLOAD.tar.xz
        sudo mkdir -p /opt/VulkanSDK
        sudo tar -xvf vulkansdk-linux-x86_64-$VERSION_VULKAN_TO_DOWNLOAD.tar.xz -C /opt/VulkanSDK
        echo "VULKAN_SDK=/opt/VulkanSDK/$VERSION_VULKAN_TO_DOWNLOAD/x86_64" >> $GITHUB_ENV
        echo "PATH=$VULKAN_SDK/bin:$PATH" >> $GITHUB_ENV
        if [ -n "${{ inputs.components }}" ]; then
          sudo bash /opt/VulkanSDK/$VERSION_VULKAN_TO_DOWNLOAD/setup-env.sh --install-components "${{ inputs.components }}"
        fi

    # macos
    - name: Install Vulkan SDK (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        curl -LO https://sdk.lunarg.com/sdk/download/$VERSION_VULKAN_TO_DOWNLOAD/mac/vulkansdk-macos-$VERSION_VULKAN_TO_DOWNLOAD.zip
        unzip vulkansdk-macos-$VERSION_VULKAN_TO_DOWNLOAD.zip -d /Applications/VulkanSDK
        if [[ "${{ inputs.components }}" == *"Vulkan-Headers"* ]]; then
          brew install vulkan-validationlayers
        fi
        for component in $(echo "${{ inputs.components }}" | tr ',' ' '); do
          if [[ "$component" != "Vulkan-Headers" && "$component" != "Vulkan-Loader" ]]; then
            brew install "$component"
          fi
        done
        echo "VULKAN_SDK=/Applications/VulkanSDK/$VERSION_VULKAN_TO_DOWNLOAD/macOS" >> $GITHUB_ENV
        echo "PATH=$VULKAN_SDK/bin:$PATH" >> $GITHUB_ENV

    # cache
    - name: Cache Vulkan SDK
      if: inputs.cache == 'true'
      uses: actions/cache@v4.2.2
      with:
        path: |
          ${{ runner.os == 'Windows' && 'C:\\VulkanSDK\\$VERSION_VULKAN_TO_DOWNLOAD' || '' }}
          ${{ runner.os == 'Linux' && '/opt/VulkanSDK/$VERSION_VULKAN_TO_DOWNLOAD/x86_64' || '' }}
          ${{ runner.os == 'macOS' && '/Applications/VulkanSDK/$VERSION_VULKAN_TO_DOWNLOAD/macOS' || '' }}
        key: vulkan-sdk-$VERSION_VULKAN_TO_DOWNLOAD-${{ runner.os }}