name: 'Test Vulkan SDK Installation'

on:
  - push
  - pull_request

jobs:
  install-vulkan-sdk:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: ['latest', '1.3.296.0']
        components: ['Vulkan-Headers,Vulkan-Loader']

    steps:
    - name: Set up Vulkan SDK
      uses: SpargatGroup/setup-vulkan-sdk@latest
      with:
        version: ${{ matrix.version }}
        components: ${{ matrix.components }}
        cache: 'true'
        
    - name: Test Vulkan SDK
      run: |
        echo $VULKAN_SDK
        echo $VERSION_VULKAN_TO_DOWNLOAD