name: 'Test Vulkan SDK Installation'

on:
  - push
  - pull_request

jobs:
  install-vulkan-sdk:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: ['latest']
        components: ['Vulkan-Headers,Vulkan-Loader']

    steps:
    - name: Set up Vulkan SDK
      uses: SpargatTeam/setup-vulkan-sdk@main
      with:
        version: ${{ matrix.version }}
        components: ${{ matrix.components }}
        cache: 'true'
        
    - name: Test Vulkan SDK
      run: echo $VULKAN_SDK